server:
  port: 8001

# 文件路径
path:
  #日志文件路径
  logPath: /home/musicroom/log
  #文件上传路径
  uploadPath: /home/musicroom/uploadFile

spring:
  profiles:
    active: @packageEnv@
  application:
    name: musicroom-admin
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: file:${path.uploadPath},/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB 

mybatis-plus: 
  mapper-locations: classpath:com/chuangxin/musicroom/*/mapper/xml/*Mapper.xml
  configuration:
    #解决，查询返回结果含null没有对应字段值问题  
    callSettersOnNulls: true
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: false
      